### ISSUE TITLE
Upgrade HPC to Ubuntu 18.04.2 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by kipkurui** [mbbu/HPC_ToDo#1]
The latest server is Ubuntu 18.04 for the HPC. To do this, we must get the following done:
- [ ] Find a way of backing up all the data currently available in the system
- [ ] Acquire a master node server that will support the use of job management system
- [ ] Set the system up, and reinstall all the necessary software required (Explore if there is a way of transferring current users to the upgraded server).
- [ ] Set up the job management system and recreate users
- [ ] Explore a solution for the cold storage

**Comment by espirado** [comment]
Hi @kipkurui can you do a write up on the system requirements for the upgrade based on the training requirements then i can make a full system requirements documentation for the upgrade.

**Comment by kipkurui** [comment]
Hey @espirado. I am checking to see if we can still work with the CentOS server for this training, and plan an update based on the overall need and not just the training. See the email conversation you are CCed.
