### ISSUE TITLE
Installing some R Packages in the Qiime environment

### ISSUE THREAD

**Issue by kipkurui** [mbbu/HPC_ToDo#10]
The packages are DECIPHER and phangorn, which are the packages required for the last step of [this pipeline](https://iallali.github.io/DADA2_pipeline/16SrRNA_DADA2_pipeline.html). @espirado, are you around to assist?

**Comment by espirado** [comment]
Am not around yet but il be there before thursday most probably.

**Comment by wanjauk** [comment]
In addition to the above packages, these packeges are also required in downstream analysis: metagenomeSeq, vegan, ggplot2, dplyr, gridExtra and renozao/NMF@devel.

**Comment by espirado** [comment]
The packages have been installed on the R module in the hpc. Any person using R installed on the hpc can use them. I have managed to installed all the packages except phangorn which there is some errors compiling the package due to the gcc environment but am hoping i will resolve it by tomorrow.

**Comment by kipkurui** [comment]
Thanks Andrew. You can also try and set them up in the conda environment, which could be easier to set up.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
