### ISSUE TITLE
Automate HPC users setup.

### ISSUE THREAD

**Issue by kipkurui** [mbbu/HPC_ToDo#11]
We can setup a script that creates user accounts after the user fills the form, and the account is approved. See this resource: https://www.cyberciti.biz/faq/rhel-debian-force-users-to-change-passwords/

**Comment by espirado** [comment]
Created  a file that takes in a username
A script that creates an account
A script that generates the password 
A script that forces the user to change the password

**Comment by kipkurui** [comment]
Thanks Andrew
