### ISSUE TITLE
Data Carpentries - Genomics 2019-12-10; Software Installations & Setup

### ISSUE THREAD

**Issue by ousodaniel** [mbbu/HPC_ToDo#12]
Hi @kipkurui, @espirado 

Kindly we will need [these](https://datacarpentry.org/genomics-workshop/setup.html) Software available for 23 training participants for the workshop, can this be set up by when, please?

The data is also available [here](https://figshare.com/articles/Data_Carpentry_Genomics_beta_2_0/7726454)

Thanks

**Comment by kipkurui** [comment]
Software | Version | Manual | Available for | Description
-- | -- | -- | -- | --
FastQC | 0.11.7 | Link | Linux, MacOS, Windows | Quality control tool for high throughput sequence data.
Trimmomatic | 0.38 | Link | Linux, MacOS, Windows | A flexible read trimming tool for Illumina NGS data.
BWA | 0.7.17 | Link | Linux, MacOS | Mapping DNA sequences against reference genome.
SAMtools | 1.9 | Link | Linux, MacOS | Utilities for manipulating alignments in the SAM format.
BCFtools | 1.8 | Link | Linux, MacOS | Utilities for variant calling and manipulating VCFs and BCFs.
IGV | Link | Link | Linux, MacOS, Windows | Visualization and interactive exploration of large genomics datasets.
