### ISSUE TITLE
Setting Up a Galaxy Instance

### ISSUE THREAD

**Issue by kipkurui** [mbbu/HPC_ToDo#17]

**Comment by espirado** [comment]
Slurm installation errrors description and setting of cpu variables

**Comment by espirado** [comment]
Galaxy set up fail to load application on localhost but actively running. Resolving to install with IRIDA . Reviewing installation guide from galaxy Africa

**Comment by espirado** [comment]
> Slurm installation errrors description and setting of cpu variables

Installed slurm

**Comment by espirado** [comment]
Galaxy configuration files organization for the hpc. Using the galaxy guide to get a picture on how to efficiently deploy galaxy for hpc

**Comment by espirado** [comment]
Set up ansible to automate software deployment,roles and tasks for galxy

**Comment by espirado** [comment]
Deploy galaxy with ansible

**Comment by espirado** [comment]
Deployed galaxy instance

**Comment by kipkurui** [comment]
Good work @espirado, thanks.
