### ISSUE TITLE
Installed packages on conda environmeent not accessible in Jupyter Notebooks

### ISSUE THREAD

**Issue by kipkurui** [mbbu/HPC_ToDo#19]
Hi Andrew. 

Been testing the Jupyer HUb, and it seems when I create an environment and install packages, they don't seem to be accessible on my notebooks. Any ideas? 

PS: Am I still in the sudoers list?

**Comment by espirado** [comment]
> Hi Andrew.
> 
> Been testing the Jupyer HUb, and it seems when I create an environment and install packages, they don't seem to be accessible on my notebooks. Any ideas?
> 
> PS: Am I still in the sudoers


yes you are still in the sudo user.  You have to activate the user environment then you can install the packages there. Refer to [hpc_set_documentation](https://github.com/mbbu/HPC-Setup-Documentation/blob/master/Jupyterhub-set-up.md)

**Comment by espirado** [comment]
To be opened when users get access to jupyter server
