### ISSUE TITLE
Setting up cluster for hosting 16s classrom

### ISSUE THREAD

**Issue by espirado** [mbbu/HPC_ToDo#20]
Documentations and links for how we are preparing our cluster for running the various sequences jobs for 16s

**Comment by kipkurui** [comment]
Thanks @espirado. Let's create a list of all the tools we need to set up.

**Comment by espirado** [comment]
Error executing process > 'filterAndTrim (filterAndTrim)'

Caused by:  Failed to pull singularity image  command: singularity pull  --name quay.io-cbio-16s-rdna-dada2-pipeline.img docker://quay.io/cbio/16s-rdna-dada2-pipeline
> /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://quay.io/cbio/16s-rdna-dada2-pipeline: Error reading manifest latest in quay.io/cbio/16s-rdna-dada2-pipeline: unauthorized: access to the requested resource is not authorized



Error after running the pipeline. It is related with registry access to the image

**Comment by espirado** [comment]
> Error executing process > 'filterAndTrim (filterAndTrim)'
> 
> Caused by: Failed to pull singularity image command: singularity pull --name quay.io-cbio-16s-rdna-dada2-pipeline.img docker://quay.io/cbio/16s-rdna-dada2-pipeline
> 
> > /dev/null
> > status : 255
> > message:
> > FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://quay.io/cbio/16s-rdna-dada2-pipeline: Error reading manifest latest in quay.io/cbio/16s-rdna-dada2-pipeline: unauthorized: access to the requested resource is not authorized
> 
> Error after running the pipeline. It is related with registry access to the image

The dada2 docker image is no longer accessible in the url for singularity pull request.

**Comment by kipkurui** [comment]
Hi @espirado. Kindly share with me the setup documentation for 16S they shared with you.
