### ISSUE TITLE
Request to install Recombination Detection Program

### ISSUE THREAD

**Issue by winfrednyoroka** [mbbu/HPC_ToDo#28]
Andrew help with installing RDP on the server. Its GUI based.

**Comment by kipkurui** [comment]
Thanks @winfrednyoroka. Please provide additional info. 
- Version 
- Link to the download page and some documentations
- Any useful info that will make setup easy.

**Comment by espirado** [comment]
@winfrednyoroka could clarify if this is the tool you want 
_RDP Classifier
RDP Classifier is a naive Bayesian classifier that can rapidly and accurately provides taxonomic assignments from domain to genus, with confidence estimates for each assignment._

**Comment by winfrednyoroka** [comment]
RDP means Recombination Detection program.
Here is the URL: http://web.cbio.uct.ac.za/~darren/rdp.html (install the stable release RDP V4.101)

**Comment by espirado** [comment]
> RDP means Recombination Detection program.
> Here is the URL: http://web.cbio.uct.ac.za/~darren/rdp.html (install the stable release RDP V4.101)

The url seems not to be working

**Comment by winfrednyoroka** [comment]
It works from my end: http://web.cbio.uct.ac.za/~darren/rdp.html
Copy the link and paste on web browser

**Comment by espirado** [comment]
support for rhel7 for rdp tool is not adequate with the current graphic adapters in the servers. Consider running it on a window machine. 

_issue to be reopened upon satisfying all requirements _
