### ISSUE TITLE
REQUEST TO INSTALL  TOOLS

### ISSUE THREAD

**Issue by fredrickkebaso** [mbbu/HPC_ToDo#29]
Hi, kindly help us in installing the following tools required in our min-project:
- kallisto,  download link  :  https://github.com/pachterlab/kallisto/releases/download/v0.46.2/kallisto_linux-v0.46.2.tar.gz
- salmon, download link : https://github.com/COMBINE-lab/salmon/releases/download/v1.4.0/salmon-1.4.0_linux_x86_64.tar.gz
- Trimgalore    downloa link : https://github.com/FelixKrueger/TrimGalore/archive/0.6.6.tar.gz
- subread package (for R analysis)  download link  : https://sourceforge.net/projects/subread/files/subread-2.0.1/subread-2.0.1-Linux-x86_64.tar.gz/download

Thank you,

**Comment by espirado** [comment]
**for trimgalore    just run 
_trim_galore_

**



all modules set up
