### ISSUE TITLE
Setting Up Singularity

### ISSUE THREAD

**Issue by kipkurui** [mbbu/HPC_ToDo#3]
For Advanced H3ABioNet training, we will need to set up Singularity. See [this documentation](http://hpcugent.github.io/vsc_user_docs/pdf/intro-HPC-linux-gent.pdf) for HPC set up that can be useful here as well. Let's make a plan for setting this up as well.

**Comment by kipkurui** [comment]
[Here is documentation](https://sylabs.io/guides/3.0/user-guide/installation.html) we can use. Let's chat up on this next week when I come back. @espirado

**Comment by espirado** [comment]
Done installing version 3.2.1 stable version on hpc.

**Comment by kipkurui** [comment]
Thanks @espirado!

**Comment by kipkurui** [comment]
Hey @espirado, kindly provide clear documentation on how you set up Singularity. Is it added as a module?

**Comment by espirado** [comment]
Hey @kipkurui, i have already documented the installation guide for the hpc. it has usage commands that it uses to build. i installed it directly from the hosted github source
