### ISSUE TITLE
Request to install Prinseq, Chimeraslayer and Pear

### ISSUE THREAD

**Issue by BryanAbuchery** [mbbu/HPC_ToDo#33]
Please assist to install Prinseq and Pear for 16S data analysis on HPC.
Prinseq: https://anaconda.org/bioconda/prinseq
Chimeraslayer : https://www.howtoinstall.me/ubuntu/18-04/chimeraslayer/
Pear: https://anaconda.org/bioconda/pear

@kipkurui

**Comment by espirado** [comment]
chimeraslayer issue [https://www.cgl.ucsf.edu/pipermail/chimera-users/2017-June/013605.html] (does not run on cent os 7)

all other tools installed
