### ISSUE TITLE
Installing Slurm on the Hpc

### ISSUE THREAD

**Issue by kipkurui** [mbbu/HPC_ToDo#7]
Hi Andrew! We can explore using a VM machine as the master for Slurm. Here are some resources that can be useful. 

1. https://www.strike3d.it/index.php/en/2018/11/06/slurm-on-centos-6/
 2. https://slurm.schedmd.com/SLUG15/SlurmVM.pdf
2. https://github.com/ciemat-tic/codec/wiki/Slurm-on-Virtual-Machines
3. https://mussolblog.wordpress.com/2013/07/17/setting-up-a-testing-slurm-cluster/
4.

**Comment by kipkurui** [comment]
The answer to this question is something we can also explore. https://stackoverflow.com/questions/42465777/how-to-setup-hpc-cluster-on-one-server 

We can explore this solution since we only have a single server.

**Comment by espirado** [comment]
Installed slurm on hpc-single cluster configuring job scheduling schemes
